name: Run Postman API Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman-tests:
    name: Run Newman Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: |
            npm install -g newman
            npm install -g newman-reporter-html


      - name: Run API Tests and Generate HTML Report
        run: |
          echo "Creating reports directory..."
          mkdir -p reports
          echo "Running Newman collection..."
          newman run BookReservationSystem.postman_collection.json \
            -e BookReservationSystemEnvironment.postman_environment.json \
            --reporters cli,html \
            --reporter-html-export reports/newman-report.html
          echo "List contents of reports directory:"
          ls -R reports

      - name: Upload Newman HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: reports
